import { readdir, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import * as path from 'path';

// Directory where to look for SVGs
// This is the NPM package directory where the SVGs are stored
const svgDirectory = path.join('node_modules', 'iconoir', 'icons', 'regular');

const run = async () => {
    
	console.log(`Finding icons for icon pack in directory: '${svgDirectory}'`);

    // Construct the path to the JSON file
    const jsonFilePath = path.join('node_modules', 'iconoir', 'package.json');

    // Read the file and parse its contents
    const jsonData = JSON.parse(readFileSync(jsonFilePath, 'utf8'));
    const version = jsonData.version;
    console.log('Iconoir NPM Version', version);

    const buildTime = new Date().toISOString();

    const iconMetadata = await fetchIconMetadata(version);

    // Read all .svgs in the directory
    const iconFiles = readdir(svgDirectory, (err, files) => {
        if (err) {
            console.error('Could not read directory', err);
            return;
        }

        const svgFiles = files.filter(file => path.extname(file) == ".svg");
        const svgFileCount = svgFiles.length;
        console.log(`Found ${svgFileCount} .svg files in directory`);

        if(svgFileCount === 0) {
            console.error('No .svg files found in directory');
            return;
        }

        GenerateSvgJsModules(svgFiles, buildTime, version);

        GenerateIconDictionary(svgFiles, buildTime, version, iconMetadata);

        UpdateUmbracoPackageVersionWithNpmVersion(version);
    });    
};

function GenerateSvgJsModules(svgFileNames, buildTime, version) {

    console.log('Generating inline icon svgs in JS modules');

    // Ensure folder exists
    if (!existsSync('./public/Iconoir')){
        console.log('Creating directory: ./public/Iconoir');
        mkdirSync('./public/Iconoir', { recursive: true })
    }
    
    svgFileNames.forEach(svgFile => {
        // Open the file and read the content
        // svgDirectory + svgFile = full path to the file
        const filePath = path.join(svgDirectory, svgFile);
        let fileContent = readFileSync(filePath, 'utf8');

        // Remove width and height attributes from the SVG
        fileContent = fileContent.replace('width="24"', '');
        fileContent = fileContent.replace('height="24"', '');

        // Create a new .js module file with the svg content
        const baseName = path.basename(svgFile, '.svg');
        const jsFilePath = `./public/Iconoir/${baseName}.js`;
        const jsFileContent = `// This file is automatically generated by 'npm run build:iconpack'
// Generated at ${buildTime}
// Iconoir NPM Version: ${version}
export default \`${fileContent}\`;`;

        // Write the content to the .js file
        writeFileSync(jsFilePath, jsFileContent, (err) => {
            if (err) {
                console.error('Error writing file:', err);
            }
        });
    });
};

function GenerateIconDictionary(svgFileNames, buildTime, version, iconMetadata){

    console.log('Generating icon dictionary .ts file');

    // Initialize an empty array for the icon dictionary
    const icons = [];

    // Iterate over the SVG file names
    svgFileNames.forEach(fileName => {
        // Remove the .svg extension from the file name
        const baseName = path.basename(fileName, '.svg');

        // Create an object for the icon
        const icon = {
            name: `iconoir-${baseName}`,
            path: `/App_Plugins/Umbraco.IconPack.Iconoir/Iconoir/${baseName}.js`,
        };

        // Enrich with keywords and groups from the Iconoir CSV when available.
        // Umbraco 17.4+ uses these for enhanced semantic icon search; older
        // versions simply ignore the extra fields.
        const meta = iconMetadata.get(baseName);
        if (meta) {
            if (meta.keywords.length > 0) icon.keywords = meta.keywords;
            if (meta.groups.length > 0) icon.groups = meta.groups;
        }

        // Add the icon object to the icon dictionary
        icons.push(icon);
    });

    // Convert the icons array into a string
    const iconArrayString = JSON.stringify(icons, null, 2);

    // Create the content for the icons.ts file
    const fileContent = `// This file is automatically generated by 'npm run build:iconpack'
// Generated at ${buildTime}
// Iconoir NPM Version: ${version}
import { UmbIconDictionary } from "@umbraco-cms/backoffice/icon";

const icons: UmbIconDictionary = ${iconArrayString};
export default icons;`;


    // Write the content to the icons.ts file
    writeFileSync('./src/IconPacks/icons.ts', fileContent, (err) => {
        if (err) {
            console.error('Error writing file:', err);
        }
    });
}

/**
 * Fetches the Iconoir icons.csv from GitHub, which maps each icon filename to
 * its category and comma-separated search tags. Tries the version-tagged URL
 * first (so the metadata matches the exact npm release in use), then falls back
 * to the main branch, and finally returns an empty Map so the build still
 * succeeds when the network is unavailable or the tag doesn't exist yet.
 */
async function fetchIconMetadata(version) {
    const urls = [
        `https://raw.githubusercontent.com/iconoir-icons/iconoir/v${version}/iconoir.com/icons.csv`,
        'https://raw.githubusercontent.com/iconoir-icons/iconoir/main/iconoir.com/icons.csv',
    ];

    for (const url of urls) {
        try {
            console.log(`Fetching icon metadata from: ${url}`);
            const response = await fetch(url);
            if (!response.ok) {
                console.warn(`Got HTTP ${response.status} from ${url}, trying next URL`);
                continue;
            }
            const csvText = await response.text();
            const metadata = parseIconCsv(csvText);
            console.log(`Fetched icon metadata for ${metadata.size} icons`);
            return metadata;
        } catch (e) {
            console.warn(`Failed to fetch from ${url}: ${e.message}`);
        }
    }

    console.warn('Could not fetch icon metadata — keywords/groups will be omitted from this build');
    return new Map();
}

function parseIconCsv(csvText) {
    const metadata = new Map();
    const lines = csvText.split('\n');

    // Skip header row: filename,category,tags
    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;

        const [filename, category, tagsRaw] = parseCsvLine(line);
        if (!filename) continue;

        const keywords = (tagsRaw ?? '')
            .split(',')
            .map(t => t.trim())
            .filter(t => t.length > 0);

        metadata.set(filename.trim(), {
            keywords,
            groups: category?.trim() ? [category.trim()] : [],
        });
    }

    return metadata;
}

// Splits a single CSV line into fields, respecting double-quoted fields that
// may contain commas (e.g. the tags column: "fly,jet,plane").
function parseCsvLine(line) {
    const fields = [];
    let current = '';
    let inQuotes = false;

    for (let i = 0; i < line.length; i++) {
        const char = line[i];
        if (char === '"') {
            inQuotes = !inQuotes;
        } else if (char === ',' && !inQuotes) {
            fields.push(current);
            current = '';
        } else {
            current += char;
        }
    }
    fields.push(current);
    return fields;
}

function UpdateUmbracoPackageVersionWithNpmVersion(version) {
    // Construct the path to the JSON file
    const jsonFilePath = path.join('public', 'umbraco-package.json');

    // Read the file and parse its contents
    const jsonData = JSON.parse(readFileSync(jsonFilePath, 'utf8'));

    // Update the version in the JSON object
    jsonData.version = version;

    // Save the JSON back down to a file
    writeFileSync(jsonFilePath, JSON.stringify(jsonData, null, 2), (err) => {
        if (err) {
            console.error('Error writing file:', err);
        }
    });
}

run();